'use client';
import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, BarChart3, Check, CheckCircle2, ChevronRight, CircleAlert, Clock3, FileText, GripVertical, LayoutList, MoreHorizontal, Pause, Pencil, Play, Plus, Radio, Settings, Trash2, Users, X } from 'lucide-react';

type Moment={id:number;title:string;duration:number;owner:string;details:string;done?:boolean};
type Issue={id:number;time:string;type:string;description:string;status:'Aberto'|'Resolvido'};
const initialMoments:Moment[]=[
 {id:1,title:'Abertura da sala',duration:10,owner:'Equipe de recepção',details:'Fundo padrão e Spotify abertura',done:true},
 {id:2,title:'Countdown',duration:5,owner:'Mídia',details:'Vídeo countdown padrão',done:true},
 {id:3,title:'Abertura',duration:5,owner:'Giseli',details:'Boas-vindas e oração',done:true},
 {id:4,title:'Adoração',duration:40,owner:'João e Hellen',details:'Fundos + letras • Voz e violão'},
 {id:5,title:'Oferta',duration:5,owner:'Fernanda Correia',details:'Fundo padrão + dados bancários'},
 {id:6,title:'Fluxo da oferta',duration:3,owner:'João e Hellen',details:'Porque Ele vive (D)'},
 {id:7,title:'Avisos e transição',duration:5,owner:'Lucas Correia',details:'Engajamento bíblico e avisos'},
 {id:8,title:'Palavra',duration:40,owner:'Josh Veras',details:'Fundo padrão + palavra'},
 {id:9,title:'Encerramento',duration:5,owner:'Josh Veras',details:'Fila de ministração'},
];
const prepSeed=[['Palco','Mesa e água posicionadas',false],['Palco','Púlpito conferido',true],['Mídia','Apresentação e letras testadas',true],['Mídia','Vídeo countdown testado',true],['Som','Microfones e retornos testados',true],['Som','Instrumentos e pedais conferidos',true],['Pessoas','Pregador confirmou presença',true],['Pessoas','Todos os responsáveis avisados',true],['Recepção','Portas e equipe posicionadas',true]] as const;
const nav=[['live','Operação ao vivo',Radio],['schedule','Cronograma',LayoutList],['prep','Preparação',CheckCircle2],['issues','Problemas',CircleAlert],['report','Relatório',BarChart3]] as const;
function asTime(start:string,plus:number){const[h,m]=start.split(':').map(Number);const total=h*60+m+plus;return `${String(Math.floor(total/60)%24).padStart(2,'0')}:${String(total%60).padStart(2,'0')}`}

export default function Home(){
 const[view,setView]=useState('live');const[moments,setMoments]=useState(initialMoments);const[current,setCurrent]=useState(3);const[seconds,setSeconds]=useState(1122);const[running,setRunning]=useState(false);const[editing,setEditing]=useState<Moment|null>(null);const[prep,setPrep]=useState(prepSeed.map((x,i)=>({id:i,team:x[0],text:x[1],done:x[2]})));const[issues,setIssues]=useState<Issue[]>([{id:1,time:'19:52',type:'Mídia',description:'Arquivo do countdown precisou ser reiniciado.',status:'Resolvido'}]);const[issueOpen,setIssueOpen]=useState(false);const[start]='19:45';
 useEffect(()=>{if(!running)return;const t=setInterval(()=>setSeconds(s=>Math.max(0,s-1)),1000);return()=>clearInterval(t)},[running]);
 const timings=useMemo(()=>{let sum=0;return moments.map(m=>{const time=asTime(start,sum);sum+=m.duration;return{...m,time,end:asTime(start,sum)}})},[moments]);const total=moments.reduce((a,m)=>a+m.duration,0);const prepared=prep.filter(x=>x.done).length;const active=timings[current];const next=timings[current+1];
 function saveMoment(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const data={id:editing?.id??Date.now(),title:String(f.get('title')),duration:Number(f.get('duration')),owner:String(f.get('owner')),details:String(f.get('details'))};setMoments(ms=>editing?ms.map(m=>m.id===editing.id?{...m,...data}:m):[...ms,data]);setEditing(null)}
 function complete(){setMoments(ms=>ms.map((m,i)=>i===current?{...m,done:true}:m));if(current<moments.length-1){setCurrent(current+1);setSeconds(moments[current+1].duration*60);setRunning(false)}}
 function addIssue(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setIssues(v=>[{id:Date.now(),time:new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'}),type:String(f.get('type')),description:String(f.get('description')),status:'Aberto'},...v]);setIssueOpen(false)}
 return <main className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">O</span><span>Ordem</span></div><nav>{nav.map(([id,label,Icon])=><button key={id} className={`nav-item ${view===id?'active':''}`} onClick={()=>setView(id)}><Icon size={17}/>{label}{id==='issues'&&issues.some(i=>i.status==='Aberto')?<b className="nav-dot"/>:null}</button>)}</nav><div className="side-caption"><span>PRÓXIMO CULTO</span><strong>Domingo, 13 set</strong><small>19:45 • Rascunho</small></div><div className="sidebar-footer"><div className="avatar">LC</div><div><strong>Lucas Correia</strong><small>Manager</small></div><Settings size={15}/></div></aside>
 <section className="workspace"><header className="topbar"><div><p className="eyebrow">CULTO DE DOMINGO</p><h1>Ekletos • 06 set 2026</h1></div><div className="top-actions"><span className="status-pill"><span/> Equipe conectada</span><button className="ghost-btn" onClick={()=>setView('schedule')}>Editar cronograma</button><button className="icon-btn"><MoreHorizontal size={19}/></button></div></header>
 <div className="page-wrap">{view==='live'&&<><div className="content-grid"><section className="main-column"><div className="live-card"><div className="live-top"><span className="live-label"><Radio size={14}/> AGORA • {active.time}</span><span className="ahead">No horário</span></div><div className="live-body"><div><p>{active.title}</p><h2>{active.owner}</h2><span>{active.details}</span></div><div className="timer"><strong>{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</strong><span>de {active.duration}:00</span></div></div><div className="progress"><i style={{width:`${100-seconds/(active.duration*60)*100}%`}}/></div><div className="live-actions"><button className="primary-btn" onClick={()=>setRunning(!running)}>{running?<Pause size={16} fill="currentColor"/>:<Play size={16} fill="currentColor"/>}{running?'Pausar':'Iniciar cronômetro'}</button><button className="secondary-btn" onClick={complete}>Concluir momento</button><button className="issue-button" onClick={()=>setIssueOpen(true)}><AlertTriangle size={15}/> Registrar problema</button></div></div><div className="section-heading"><div><p className="eyebrow">ROTEIRO</p><h3>Cronograma do culto</h3></div><span className="summary-time">Término previsto {asTime(start,total)}</span></div><div className="schedule-list">{timings.map((item,i)=><div className={`schedule-row ${item.done?'done':''} ${i===current?'live':''}`} key={item.id}><div className="time"><strong>{item.time}</strong><span>{item.duration} min</span></div><div className="node">{item.done?<Check size={13}/>:i===current?<span/>:null}</div><div className="moment"><strong>{item.title}</strong><span>{item.owner}</span></div><button className="row-btn" onClick={()=>setCurrent(i)}><ChevronRight size={17}/></button></div>)}</div></section><aside className="right-panel"><div className="next-card"><p className="eyebrow">A SEGUIR • {next?.time}</p><h3>{next?.title}</h3><p>{next?.owner}</p><div className="mini-check">{prep.slice(0,3).map(x=><span key={x.id} className={!x.done?'pending':''}>{x.done?<Check size={14}/>:<i/>}{x.text}</span>)}</div><button onClick={()=>setView('prep')}>Ver preparação <ChevronRight size={15}/></button></div><div className="attention-card"><div className="attention-icon"><CheckCircle2 size={18}/></div><div><strong>{prepared===prep.length?'Tudo preparado':`${prepared} de ${prep.length} itens prontos`}</strong><p>{prepared===prep.length?'A equipe confirmou todos os itens.':'Revise os itens pendentes antes do próximo momento.'}</p></div></div></aside></div></>}
 {view==='schedule'&&<ScheduleView timings={timings} total={total} start={start} setEditing={setEditing} setMoments={setMoments}/>} {view==='prep'&&<PrepView prep={prep} setPrep={setPrep}/>} {view==='issues'&&<IssuesView issues={issues} setIssues={setIssues} open={()=>setIssueOpen(true)}/>} {view==='report'&&<ReportView moments={moments} timings={timings} issues={issues} prepared={prepared} prepTotal={prep.length}/>}</div></section>
 {editing!==null&&<MomentModal moment={editing.id===0?null:editing} close={()=>setEditing(null)} save={saveMoment}/>} {issueOpen&&<IssueModal close={()=>setIssueOpen(false)} save={addIssue}/>}</main>
}

function ScheduleView({timings,total,start,setEditing,setMoments}:{timings:(Moment&{time:string;end:string})[];total:number;start:string;setEditing:(m:Moment)=>void;setMoments:React.Dispatch<React.SetStateAction<Moment[]>>}){return <div className="surface"><div className="view-head"><div><p className="eyebrow">PLANEJAMENTO</p><h2>Editor de cronograma</h2><p>Organize cada momento. Os horários são recalculados automaticamente.</p></div><div className="view-actions"><button className="ghost-btn"><FileText size={15}/> Duplicar último culto</button><button className="primary-solid" onClick={()=>setEditing({id:0,title:'',duration:5,owner:'',details:''})}><Plus size={16}/> Novo momento</button></div></div><div className="timeline-summary"><div><span>Início</span><strong>{start}</strong></div><ChevronRight/><div><span>Duração</span><strong>{Math.floor(total/60)}h {total%60}min</strong></div><ChevronRight/><div><span>Término previsto</span><strong>{asTime(start,total)}</strong></div><span className="valid"><Check size={14}/> Cronograma válido</span></div><div className="editor-list">{timings.map((m)=><div className="editor-row" key={m.id}><GripVertical size={18}/><div className="editor-time"><strong>{m.time}</strong><span>até {m.end}</span></div><div className="editor-main"><strong>{m.title}</strong><span>{m.owner} • {m.details}</span></div><b>{m.duration} min</b><button onClick={()=>setEditing(m)}><Pencil size={15}/></button><button className="danger-icon" onClick={()=>setMoments(v=>v.filter(x=>x.id!==m.id))}><Trash2 size={15}/></button></div>)}</div><button className="add-row" onClick={()=>setEditing({id:0,title:'',duration:5,owner:'',details:''})}><Plus size={16}/> Adicionar momento</button></div>}
function PrepView({prep,setPrep}:{prep:{id:number;team:string;text:string;done:boolean}[];setPrep:React.Dispatch<React.SetStateAction<{id:number;team:string;text:string;done:boolean}[]>>}){const groups=[...new Set(prep.map(x=>x.team))];const ready=prep.filter(x=>x.done).length;return <div className="surface"><div className="view-head"><div><p className="eyebrow">ANTES DO CULTO</p><h2>Central de preparação</h2><p>Cada equipe confirma o que testou e preparou.</p></div><div className="readiness"><strong>{ready}/{prep.length}</strong><span>itens prontos</span></div></div><div className="readiness-bar"><i style={{width:`${ready/prep.length*100}%`}}/></div><div className="prep-grid">{groups.map(g=><section className="team-card" key={g}><div className="team-title"><div className="team-icon"><Users size={16}/></div><div><strong>{g}</strong><span>{prep.filter(x=>x.team===g&&x.done).length}/{prep.filter(x=>x.team===g).length} concluídos</span></div></div>{prep.filter(x=>x.team===g).map(x=><label className={`check-row ${x.done?'checked':''}`} key={x.id}><input type="checkbox" checked={x.done} onChange={()=>setPrep(v=>v.map(i=>i.id===x.id?{...i,done:!i.done}:i))}/><span className="fake-check">{x.done&&<Check size={13}/>}</span>{x.text}</label>)}</section>)}</div></div>}
function IssuesView({issues,setIssues,open}:{issues:Issue[];setIssues:React.Dispatch<React.SetStateAction<Issue[]>>;open:()=>void}){return <div className="surface"><div className="view-head"><div><p className="eyebrow">ACOMPANHAMENTO</p><h2>Problemas e ocorrências</h2><p>Registre o que aconteceu e acompanhe a resolução.</p></div><button className="primary-solid" onClick={open}><Plus size={16}/> Registrar problema</button></div><div className="metrics"><div><strong>{issues.length}</strong><span>Total registrado</span></div><div><strong>{issues.filter(x=>x.status==='Aberto').length}</strong><span>Em aberto</span></div><div><strong>{issues.filter(x=>x.status==='Resolvido').length}</strong><span>Resolvidos</span></div></div><div className="issue-list">{issues.length===0?<div className="empty"><CheckCircle2/><strong>Nenhuma ocorrência</strong><span>Quando algo acontecer, registre aqui.</span></div>:issues.map(i=><div className="issue-row" key={i.id}><div className="issue-badge"><AlertTriangle size={16}/></div><div><span>{i.time} • {i.type}</span><strong>{i.description}</strong></div><button className={i.status==='Resolvido'?'resolved':'open-status'} onClick={()=>setIssues(v=>v.map(x=>x.id===i.id?{...x,status:x.status==='Aberto'?'Resolvido':'Aberto'}:x))}>{i.status}</button></div>)}</div></div>}
function ReportView({moments,timings,issues,prepared,prepTotal}:{moments:Moment[];timings:(Moment&{time:string;end:string})[];issues:Issue[];prepared:number;prepTotal:number}){return <div className="surface"><div className="view-head"><div><p className="eyebrow">PÓS-CULTO</p><h2>Relatório da operação</h2><p>Resumo automático para a liderança.</p></div><button className="primary-solid"><FileText size={16}/> Exportar relatório</button></div><div className="report-hero"><div><span>Pontualidade</span><strong>No horário</strong><small>Início 19:45 • Término previsto {timings.at(-1)?.end}</small></div><div className="score">92<small>/100</small></div></div><div className="metrics four"><div><strong>{moments.filter(x=>x.done).length}/{moments.length}</strong><span>Momentos concluídos</span></div><div><strong>{prepared}/{prepTotal}</strong><span>Preparação</span></div><div><strong>{issues.length}</strong><span>Ocorrências</span></div><div><strong>{issues.filter(x=>x.status==='Aberto').length}</strong><span>Pendências</span></div></div><section className="feedback-box"><p className="eyebrow">FEEDBACK DO MANAGER</p><textarea placeholder="Conte para a liderança o que funcionou bem, o que precisa melhorar e quais decisões devem ser tomadas no próximo culto..."/><button className="primary-solid">Salvar feedback</button></section></div>}
function MomentModal({moment,close,save}:{moment:Moment|null;close:()=>void;save:(e:React.FormEvent<HTMLFormElement>)=>void}){return <div className="modal-backdrop"><form className="modal" onSubmit={save}><div className="modal-head"><div><p className="eyebrow">CRONOGRAMA</p><h3>{moment?'Editar momento':'Novo momento'}</h3></div><button type="button" onClick={close}><X/></button></div><label>Nome do momento<input name="title" required defaultValue={moment?.title}/></label><div className="form-grid"><label>Duração (min)<input name="duration" type="number" min="1" required defaultValue={moment?.duration??5}/></label><label>Responsável<input name="owner" required defaultValue={moment?.owner}/></label></div><label>Orientações para a equipe<textarea name="details" defaultValue={moment?.details}/></label><div className="modal-actions"><button type="button" className="ghost-btn" onClick={close}>Cancelar</button><button className="primary-solid">Salvar momento</button></div></form></div>}
function IssueModal({close,save}:{close:()=>void;save:(e:React.FormEvent<HTMLFormElement>)=>void}){return <div className="modal-backdrop"><form className="modal" onSubmit={save}><div className="modal-head"><div><p className="eyebrow">OCORRÊNCIA</p><h3>Registrar problema</h3></div><button type="button" onClick={close}><X/></button></div><label>Área<select name="type"><option>Palco</option><option>Mídia</option><option>Som</option><option>Pessoas</option><option>Horário</option><option>Outro</option></select></label><label>O que aconteceu?<textarea name="description" required placeholder="Descreva de forma objetiva..."/></label><div className="modal-actions"><button type="button" className="ghost-btn" onClick={close}>Cancelar</button><button className="primary-solid">Registrar ocorrência</button></div></form></div>}
