'use client';
import { useEffect,useState } from 'react';
import { Ban,Check,Copy,Link2,Plus,Search,ShieldCheck,UserPlus,Users } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog,DialogContent,DialogDescription,DialogTitle } from '@/components/ui/dialog';

type Role='admin'|'manager'|'volunteer';
type Area={id:string;name:string;color:string;active:boolean};
type Access={email:string;role:Role;created_at:string};
type Pending={email:string;name:string;created_at:string;confirmed:boolean;area_ids:string[]};
type Invite={id:string;token:string;email:string|null;role:Role;area_ids:string[];expires_at:string;used_at:string|null;used_by:string|null};
export const roleLabel:Record<Role,string>={admin:'Administrador',manager:'Operador',volunteer:'Somente leitura'};
const roleText:Record<Role,string>={admin:'Controla usuários, áreas e todo o sistema.',manager:'Edita cultos, escalas e conduz a operação.',volunteer:'Consulta as informações sem alterar o planejamento.'};
function AreaChecks({areas,selected,change}:{areas:Area[];selected:string[];change:(ids:string[])=>void}){return <fieldset className="area-checks"><legend>Áreas em que serve</legend>{areas.filter(x=>x.active).map(a=><label key={a.id}><input type="checkbox" checked={selected.includes(a.id)} onChange={e=>change(e.target.checked?[...selected,a.id]:selected.filter(id=>id!==a.id))}/><i style={{background:a.color}}/>{a.name}</label>)}</fieldset>}

export function AccessAdminPanel({email,role}:{email:string;role:string}){
 const [access,setAccess]=useState<Access[]>([]),[pending,setPending]=useState<Pending[]>([]),[areas,setAreas]=useState<Area[]>([]),[links,setLinks]=useState<Invite[]>([]),[userAreas,setUserAreas]=useState<{email:string;area_id:string}[]>([]);
 const [selected,setSelected]=useState<Record<string,string[]>>({}),[choice,setChoice]=useState<Record<string,Role>>({});
 const [search,setSearch]=useState(''),[notice,setNotice]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[inviteOpen,setInviteOpen]=useState(false);
 const [inviteAreas,setInviteAreas]=useState<string[]>([]),[newArea,setNewArea]=useState(''),[newColor,setNewColor]=useState('#2f6b57');
 async function load(){if(role!=='admin')return;const [a,p,ar,ua,i]=await Promise.all([supabase.from('zion_access').select('email,role,created_at').order('created_at'),supabase.rpc('zion_pending_users'),supabase.from('zion_areas').select('*').order('name'),supabase.from('zion_user_areas').select('*'),supabase.from('zion_access_invites').select('*').order('created_at',{ascending:false}).limit(20)]);const first=[a,p,ar,ua,i].find(x=>x.error);if(first?.error){setError(first.error.message);return;}setAccess(a.data as Access[]);setPending(p.data as Pending[]);setAreas(ar.data as Area[]);setUserAreas(ua.data||[]);setLinks(i.data as Invite[]);setSelected(Object.fromEntries((p.data as Pending[]).map(x=>[x.email,x.area_ids||[]])));}
 useEffect(()=>{void load();},[role]);
 async function setAreasFor(target:string,ids:string[]){await supabase.from('zion_user_areas').delete().eq('email',target);if(ids.length){const {error}=await supabase.from('zion_user_areas').insert(ids.map(area_id=>({email:target,area_id})));if(error)throw error;}setUserAreas(v=>[...v.filter(x=>x.email!==target),...ids.map(area_id=>({email:target,area_id}))]);}
 async function approve(person:Pending){setBusy(true);setError('');try{const permission=choice[person.email]||'volunteer';const {data,error}=await supabase.from('zion_access').insert({email:person.email,role:permission}).select().single();if(error)throw error;await setAreasFor(person.email,selected[person.email]||[]);setPending(v=>v.filter(x=>x.email!==person.email));setAccess(v=>[...v,data as Access]);setNotice(`${person.name} foi aprovado como ${roleLabel[permission]}.`);}catch(e){setError(e instanceof Error?e.message:'Não foi possível aprovar.');}finally{setBusy(false);}}
 async function createInvite(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);const days=Math.min(30,Math.max(1,Number(f.get('days'))||7));const row={email:String(f.get('email')||'').trim().toLowerCase()||null,role:String(f.get('role')) as Role,area_ids:inviteAreas,expires_at:new Date(Date.now()+days*86400000).toISOString()};const {data,error}=await supabase.from('zion_access_invites').insert(row).select().single();setBusy(false);if(error){setError(error.message);return;}setLinks(v=>[data as Invite,...v]);setInviteOpen(false);setInviteAreas([]);await copyInvite((data as Invite).token);}
 async function copyInvite(token:string){const url=`${location.origin}/?convite=${token}`;try{await navigator.clipboard.writeText(url);setNotice('Link de convite copiado.');}catch{setNotice(url);}}
 async function addArea(e:React.FormEvent){e.preventDefault();if(!newArea.trim())return;const {data,error}=await supabase.from('zion_areas').insert({name:newArea.trim(),color:newColor}).select().single();if(error){setError(error.message);return;}setAreas(v=>[...v,data as Area].sort((x,y)=>x.name.localeCompare(y.name)));setNewArea('');setNotice('Área cadastrada.');}
 async function toggleArea(area:Area){const {error}=await supabase.from('zion_areas').update({active:!area.active}).eq('id',area.id);if(error){setError(error.message);return;}setAreas(v=>v.map(x=>x.id===area.id?{...x,active:!x.active}:x));}
 async function revoke(item:Access){if(item.email===email.toLowerCase()||!confirm(`Revogar o acesso de ${item.email}?`))return;const {error}=await supabase.from('zion_access').delete().eq('email',item.email);if(error){setError(error.message);return;}setAccess(v=>v.filter(x=>x.email!==item.email));setNotice('Acesso revogado.');}
 if(role!=='admin')return null;const filtered=access.filter(x=>x.email.includes(search.toLowerCase()));const areaNames=(target:string)=>userAreas.filter(x=>x.email===target).map(x=>areas.find(a=>a.id===x.area_id)?.name).filter(Boolean);
 return <section className="access-page access-modern">
  <div className="view-head"><div><p className="eyebrow">ADMINISTRAÇÃO</p><h2>Usuários e acessos</h2><p>Todo cadastro precisa de aprovação ou de um convite emitido por você.</p></div><Button className="primary-solid" onClick={()=>setInviteOpen(true)}><Link2 size={16}/>Gerar convite</Button></div>
  <div className="access-summary"><ShieldCheck size={22}/><div><strong>Acesso protegido</strong><p>Voluntário e usuário continuam separados. As áreas mostram onde a pessoa serve; a escala define quando ela serve.</p></div><span>{access.length} com acesso</span></div>
  {!!pending.length&&<section className="pending-card"><div className="pending-head"><UserPlus size={18}/><div><strong>Aguardando sua aprovação</strong><p>Essas pessoas criaram uma conta, mas ainda não conseguem entrar.</p></div><span>{pending.length}</span></div><ul className="pending-list">{pending.map(p=><li key={p.email}><div className="pending-person"><span className="access-avatar"><Users size={17}/></span><div><strong>{p.name}</strong><small>{p.email}{!p.confirmed?' · e-mail não confirmado':''}</small></div></div><select value={choice[p.email]||'volunteer'} onChange={e=>setChoice(v=>({...v,[p.email]:e.target.value as Role}))}>{Object.entries(roleLabel).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><AreaChecks areas={areas} selected={selected[p.email]||[]} change={ids=>setSelected(v=>({...v,[p.email]:ids}))}/><Button className="primary-solid" disabled={busy} onClick={()=>void approve(p)}><Check size={14}/>Aprovar</Button></li>)}</ul></section>}
  <div className="access-table-card"><div className="access-toolbar"><label className="access-search"><Search size={16}/><Input placeholder="Buscar por e-mail" value={search} onChange={e=>setSearch(e.target.value)}/></label></div><div className="access-table-scroll"><table><thead><tr><th>Usuário</th><th>Permissão</th><th>Áreas</th><th></th></tr></thead><tbody>{filtered.map(item=><tr key={item.email}><td><strong>{item.email}</strong>{item.email===email.toLowerCase()&&<small>Você</small>}</td><td><span className={`access-role ${item.role}`}>{roleLabel[item.role]}</span></td><td><div className="area-chips">{areaNames(item.email).map(x=><span key={x}>{x}</span>)}{!areaNames(item.email).length&&<em>Não informado</em>}</div></td><td><Button className="revoke-btn" disabled={item.email===email.toLowerCase()} onClick={()=>void revoke(item)}><Ban size={14}/></Button></td></tr>)}</tbody></table></div></div>
  <section className="area-admin"><div><p className="eyebrow">ÁREAS DA IGREJA</p><h3>Onde as pessoas servem</h3><p>Use estas áreas no cadastro, na aprovação e nos convites.</p></div><form onSubmit={addArea}><Input value={newArea} onChange={e=>setNewArea(e.target.value)} placeholder="Ex.: Kids, Fotografia…" maxLength={60}/><input type="color" value={newColor} onChange={e=>setNewColor(e.target.value)}/><Button className="primary-solid"><Plus size={14}/>Cadastrar</Button></form><div className="area-list">{areas.map(a=><button key={a.id} className={!a.active?'inactive':''} onClick={()=>void toggleArea(a)}><i style={{background:a.color}}/>{a.name}<small>{a.active?'Ativa':'Inativa'}</small></button>)}</div></section>
  <section className="invite-history"><p className="eyebrow">CONVITES RECENTES</p>{links.length?<ul>{links.map(i=><li key={i.id}><div><strong>{i.email||'Link para qualquer pessoa'}</strong><span>{roleLabel[i.role]} · vence em {new Date(i.expires_at).toLocaleDateString('pt-BR')}</span></div><span className={i.used_at?'used':'open'}>{i.used_at?`Aceito por ${i.used_by}`:'Disponível'}</span><Button className="ghost-btn" disabled={!!i.used_at} onClick={()=>void copyInvite(i.token)}><Copy size={13}/>Copiar</Button></li>)}</ul>:<p>Nenhum convite criado.</p>}</section>
  {notice&&<p className="access-notice" role="status">{notice}</p>}{error&&<p className="operation-error" role="alert">{error}</p>}
  <div className="access-permissions">{(Object.keys(roleLabel) as Role[]).map(r=><article key={r}><span className={`access-role ${r}`}>{roleLabel[r]}</span><p>{roleText[r]}</p></article>)}</div>
  <Dialog open={inviteOpen} onOpenChange={setInviteOpen}><DialogContent className="access-dialog"><DialogTitle>Gerar link de convite</DialogTitle><DialogDescription>Quem usar este link terá acesso com as opções definidas abaixo. Cada link funciona uma única vez.</DialogDescription><form onSubmit={createInvite}><label>E-mail específico <small>Opcional. Se preenchido, outra pessoa não poderá usar.</small><Input type="email" name="email" placeholder="nome@igreja.com"/></label><label>Permissão<select name="role" defaultValue="volunteer">{Object.entries(roleLabel).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label><AreaChecks areas={areas} selected={inviteAreas} change={setInviteAreas}/><label>Validade em dias<Input name="days" type="number" min="1" max="30" defaultValue="7"/></label><Button className="primary-solid" disabled={busy}>{busy?'Gerando…':'Gerar e copiar link'}</Button></form></DialogContent></Dialog>
 </section>;
}
